apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stock-app
  name: stock-app
  namespace: finance
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
      - image: navin772/streamlitstockapp:2.0 # Docker image name
        name: stock-preds     # POD name 
        ports:
        - containerPort: 8501
          protocol: TCP