apiVersion: v1
kind: Service
metadata:
  name: index-prediction-app
  labels:
    run: index-prediction-app
  namespace: finance  
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: index-prediction-app